### ISSUE TITLE
Issue attaching Servos

### ISSUE THREAD

**Issue by GenericSwede** [pololu/dual-vnh5019-motor-shield#19] opened 2019-12-03 10:24 UTC
I'm using this motor controller to power a basic tank robot, and I'm now trying to add a servo to it to give it some more functionality. When I added the Servo to my code the Motor Controller refused to work correctly, not outputting any current or changing the colors of the indicator LEDs. I traced the issue to the servo.attack(pin); command. I attached the servo to pins that were listed as unused on the pololu site and this issue still occurred. Is there a fix for this? Thanks.

-JM

**Comment by kevin-pololu** [comment] 2019-12-09 22:55
Hi, JM.

It looks like you posted about this [on the Pololu forum](https://forum.pololu.com/t/issue-running-servo-and-dual-vnh5019-mc/18405) and got help resolving it there. For anyone else encountering a similar problem, it is likely caused by a conflict where multiple libraries are trying to use the same timer, and that forum thread suggests some workarounds.

Kevin

**Closed by kevin-pololu** 2019-12-09 22:55 UTC
