### ISSUE TITLE
Pololu VNH5019 Motor driver shield library does not work!!!

### ISSUE THREAD

**Issue by TM3DDesign** [pololu/dual-vnh5019-motor-shield#11] opened 2016-04-24 19:05 UTC
Hello Kevin,

I purchased two Pololu Motors plus driver shield months ago and have had nothing but problems with this code you offer here. It does not work. The Arduino IDE cannot compile it the way it is compiled. I have looked for help to correct this issue for months to no avail.

There is something either corrupt in a single file or the naming conventions with the - () that were put in file names, but even if renamed, Arduino IDE cannot recognize nor upload this or any other Pololu VNH 5019 Motor driver/shield coding. The IDE will either give 'fatal error'..."no such file in directory"
or this one:
"
Arduino: 1.6.8 (Windows 8), Board: "Arduino/Genuino Uno"
C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Program Files (x86)\Arduino\libraries\libraries" -fqbn=arduino:avr:uno -ide-version=10608 -build-path "C:\Users\Trent\AppData\Local\Temp\build4db7ceb00b426b60b38c895eb1d4e961.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "C:\Program Files (x86)\Arduino\libraries\DualVNH5019MotorShield\DualVNH5019MotorShield\DualVNH5019MotorShield\examples\Demo\Demo.ino"
open C:\Program Files (x86)\Arduino\libraries\libraries: The system cannot find the file specified.

Error compiling for board Arduino/Genuino Uno.
"
I have tried everything from uninstalling/re-installing, naming convention correction you name it and the library cannot locate nor process these files.
Could you please look into this at your earliest convenience, test and post a proper code that actually works? I have been finished my project build for several weeks and have been totally held up by this infuriating issue.

Greatly appreciated.

**Comment by photodude** [comment] 2016-04-24 19:12
@TM3DDesign I'm assuming you are trying to use your two dual-vnh5019-motor-shields on one Arduino/Genuino Uno.

I would suggest you take a look at my customized version of this library which allows for using two dual-vnh5019-motor-shields at the same time. Please note the modifications for the boards listed in the description that are needed to make this configuration work. https://github.com/photodude/DualVNH5019MotorShieldMod3

**Comment by photodude** [comment] 2016-04-24 19:24
On a side note: the last version of the Arduino IDE I tested anything with was 1.6.4. I see no reason why 1.6.8 would have any issues as it should be 100% backwards compatible with existing code and libraries.

**Comment by TM3DDesign** [comment] 2016-04-24 19:24
Hi PD,

Yes you are correct. Two dual VNH5019 motors with shield. 

Doh, I have scoured this site and many others for months!! 

If this works you are GODSEND and a scholar!!!!

Thanks so much!

**Comment by TM3DDesign** [comment] 2016-04-24 19:27
I have tried so many different things to no avail, but finally got servos and HC-05 bluetooth compiled and operating recently thankfully or was at a total standstill with this library not compiling to test the motor direction, speeds, handling etc for my project. Very time consuming and most frustrating at times but knew it can work.

Thanks very much, I'll let you know when it works!
Cheers

**Comment by photodude** [comment] 2016-04-24 19:38
My custom library has worked well for my projects using two dual-vnh5019-motor-shields on one Arduino Mega. (Noting the requirement to move the PWM pins on the shields to avoid pin conflicts)

By the way, be careful of PWM pin conflicts with your setup when using servos, two motor drivers, etc.PWM pin conflicts were a major issue on one of my projects. (Arduino Mega may have a lot of pins but it's only got a few PWM pins)

See my PR for notes on PWM pin recommendations to avoid conflicts (see the PWM pin documentation for your Arduino/Genuino Uno)
https://github.com/pololu/dual-vnh5019-motor-shield/pull/9

**Comment by TM3DDesign** [comment] 2016-04-24 19:44
Oh okay, yes appreciate the headsup! I have been trying to understand the PWM more recently, especially with motors and servos...damn, like I don't have enough to worry about...lol

Btw, I got the HC-05 Bluetooth programmed for frequency and naming device etc, but also having issue with a code provided by an author on 'Instructables' for my DIY project, for the proper setup of bluetooth with arduino and gives a..." "d" does not name a type" error in IDE. But since I got the HC-05 renamed, baud rate changed it seems to work so not certain if I need to code anymore to get it all to work with motors or not?

I have the HC-05 module powered and signalling properly, associated with my phone with Arduino RC Car app and green light is on screen. Do I need anymore code or will the RC car controls just start controlling wheel direction and speeds once this 'DualMotorSHield' mod 3 is compiled, do you know this by chance? I believe I downloaded a similar one from here that you may have provided. Any mods to that one if so would be greatly appreciated as well if so/necessary. Lmk.
Thanks!

**Comment by photodude** [comment] 2016-04-24 19:51
The library just gives you access to functions for controlling motors (controlling motor direction, speeds, breaking, etc) you will still need to write your own functions to tell the program what the different commands from your Bluetooth input mean. (i.e. what functions does the Arduino need to do when you tell it do go forward? set motor direction, set speed, set servo angles, turn on an led, etc. those are all things you have to determine)

**Comment by TM3DDesign** [comment] 2016-04-24 19:58
Oh okay I figured, just hoped I had one less thing to do with coding haha

Just opened the motor test file and reading the first line:
`Motor Test Example
//#ifndef (__AVR_ATmega1280__) || ndef(__AVR_ATmega2560__)
//#error "This library only supports Arduino Mega boards."
//#endif`

I have Uno R3 (328 atmega)...I cannot use this to test...or can I just rename it to Arduino Uno R3 in code?

**Comment by TM3DDesign** [comment] 2016-04-24 21:30
Hmmm, Confused somewhat still. 
Obviously, because of the controller memory on your Mega/ your code I presume that you can just rename this in code to make it work for Uno R3 with the pololu dual driver shield and motors??
I read the pdf for these motors once again (remapped with shorting block as suggested to power through shield already and servo works on pin9, LEDs for wheels are working when turning each direction (Forward-green- red-reverse), occasionally one of the wheels will start spinning continuously until disconnected from battery (6V lead acid). Thought that once motor + - wires were connected through the headers (I had to solder directly to pins to make work) that they would both spin at same time. Is that not what they are supposed to do once all connections are made properly even without compiling the driver shield coding? And if board LED lights for motors are powering while servo spinning fine with signal jumper on pin 9 and with no overheating whatsoever, I just need this library and code to work to be on my way?
Checking header connections to rule out this once and for all.

**Comment by TM3DDesign** [comment] 2016-04-24 21:53
Servo connected with jumper on pin, 5v (works on 3.3 v also though and one of grounds on pins nearest to shorting block) I should mention...no issues. Well, outside of the cheap, poorly designed and made jumper wires available/used for these boards/pins lol

**Comment by TM3DDesign** [comment] 2016-04-24 23:04
One more question for you. 
If I cannot use pins 9 or 10 to make both servo and driver motors work in tandem, what other pins can I use without remapping pins on shield? A1 AO I have seen examples but not certain. Is there no other way to wire one servo, HC-05 and 2 motors with driver shield the way I have it wired up? The guide mentions nothing about this with the assembly/connection to Uno using shorting block with shield for power,  just learning the ins and outs of Uno R3 limitations, so very uncertain at this point with all power lights working fine right now.

**Comment by TM3DDesign** [comment] 2016-04-24 23:38
Hi Walt, 
Do you think this interrupt code perhaps do the trick to use pin 9 or 7 and without remapping PWM on board? 


http://forum.arduino.cc/index.php?topic=102430.15 


Trent 






----- Original Message -----

**Comment by photodude** [comment] 2016-04-25 00:01
Oh, ya.... Forgot about that "gotcha" on Mega use. It's been over a year since I set this up. 

The reason the code specifies #error "This library only supports Arduino Mega boards." Is due to me working with just a Mega. Things get more complex with the Uno R3 due to the small pin set. You would need to spend some time customizing the part of the library code for the pin mapping. (At least that's all I remember) 

As for the "interrupt code" I'm not sure if that would work. but here is the deal, you can't "remap" PWM on the Uno R3 or the mega, there are specified pins that can do PWM and that's it. The "remapping" on the shields is literally moving the physical connections so they can connect to a different PWM from the stock set up. Information on how to move the pins is in the pololu DualVNH5019MotorShield user guide.

**Comment by TM3DDesign** [comment] 2016-04-25 03:59
Oh I can 'easily' see why you still get those 'gotcha' moments Walt hahaha 


Default pin map - Arduino Uno R3 


Arduino Pin VNH5019 Driver Pin Basic Function 
Digital 2 M1INA Motor 1 direction input A 
Digital 4 M1INB Motor 1 direction input B 
Digital 6 M1EN/DIAG Motor 1 enable input/fault output 
Digital 7 M2INA Motor 2 direction input A 
Digital 8 M2INB Motor 2 direction input B 
Digital 9 M1PWM Motor 1 speed input 
Digital 10 M2PWM Motor 2 speed input 
Digital 12 M2EN/DIAG Motor 2 enable input/fault output 
Analog 0 M1CS Motor 1 current sense output 
Analog 1 M2CS Motor 2 current sense output 


Okay, I just had a gotcha moment when trying to reconnect the + jumper for servo. I kind of put pressure on jumper plug to board, away from board and now both motors and LEDs finally came on together, one spinning forward, one reverse and one red light, the other green. Like I mentioned I knew they were connected properly, but noticeably a fault at pin digital pin connections from shield to board as I figured would happen the half ass way these boards were designed to come together, that and being impinged on DC jack and serial usb port to get complete powering of all pins. (a reason I early on put electrical tape over rear of DC jack housing also!) The kid who did this project never mentioned having to do anything else with PWM pins (soldering the aforementioned headers onto board, nor the Ardvin/ Vout shorting block and many other things I have had to try to figure out myself and have connected everything like he did from photographs mostly, and everything works and looks like how he got it to all work together. Just this code problem is getting really annoying. 


Regardless, I didn't notice an error for code for Mega, IDE still will not recognize either of the driver shield files whether I put them in my documents arduino libraries, or the C drive Arduino libraries and just keeps saying the same things no matter what I try. I do not understand now if its because my annoying library problem or the code, the original library code for your mega project or it will actually work with Uno R3 by just renaming mega commands with uno?? 


This Mod3 library errors: 


Arduino: 1.6.8 (Windows 8), Board: "Arduino/Genuino Uno" 


C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Program Files (x86)\Arduino\libraries\libraries" -fqbn=arduino:avr:uno -ide-version=10608 -build-path "C:\Users\Trent\AppData\Local\Temp\buildef868b128bade5e52a041d29254f8adf.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "C:\Program Files (x86)\Arduino\libraries\DualVNH5019MotorShieldMod3-master\DualVNH5019MotorShieldMod3\examples\Test_Motors\Test_Motors.ino" 
open C:\Program Files (x86)\Arduino\libraries\libraries: The system cannot find the file specified. 


Error compiling for board Arduino/Genuino Uno. 
Invalid library found in C:\Program Files (x86)\Arduino\libraries\DualVNH5019MotorShield: C:\Program Files (x86)\Arduino\libraries\DualVNH5019MotorShield 
Invalid library found in C:\Program Files (x86)\Arduino\libraries\DualVNH5019MotorShieldMod3-master: C:\Program Files (x86)\Arduino\libraries\DualVNH5019MotorShieldMod3-master : 


And the original 'DualMotorShield' library 'demo' ino errors: 



Arduino: 1.6.8 (Windows 8), Board: "Arduino/Genuino Uno" 


C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware "C:\Program Files (x86)\Arduino\hardware" -tools "C:\Program Files (x86)\Arduino\tools-builder" -tools "C:\Program Files (x86)\Arduino\hardware\tools\avr" -built-in-libraries "C:\Program Files (x86)\Arduino\libraries" -libraries "C:\Program Files (x86)\Arduino\libraries\libraries" -fqbn=arduino:avr:uno -ide-version=10608 -build-path "C:\Users\Trent\AppData\Local\Temp\build4db7ceb00b426b60b38c895eb1d4e961.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "C:\Program Files (x86)\Arduino\libraries\DualVNH5019MotorShield\DualVNH5019MotorShield\DualVNH5019MotorShield\examples\Demo\Demo.ino" 
open C:\Program Files (x86)\Arduino\libraries\libraries: The system cannot find the file specified. 


Error compiling for board Arduino/Genuino Uno. 




These files are now showing up in the 'Sketchbook' drop menu...but not in the 'examples' or 'include library' drop down menus?? Losing my patience and noodle lol If you are able to look into this a bit and help me get this working I'd greatly appreciate it Walt. 


Trent 

----- Original Message -----

**Comment by photodude** [comment] 2016-04-25 05:14
Trent,
It looks like you have the library files buried in folders (or bad folder naming coming from the github zip download button), 

Your structure
```
\Arduino\libraries\DualVNH5019MotorShieldMod3-master
\Arduino\libraries\DualVNH5019MotorShield\DualVNH5019MotorShield\DualVNH5019MotorShield
```
**The correct structure**
```
\Arduino\libraries\DualVNH5019MotorShield\
```
or for my dual shields library
```
\Arduino\libraries\DualVNH5019MotorShieldMod3\
```

Tip: Use the [release zips](https://github.com/photodude/DualVNH5019MotorShieldMod3/releases) rather than directly downloading from the github projects "download zip" button; and check if the folder naming is what's expected.

I have tested compiling with Arduino IDE 1.6.8 with no issues.

**Comment by TM3DDesign** [comment] 2016-04-25 17:50
Hi Walt, 


OMG..I got it working!!! 


Yes, that was my first hint and confusion as it kept saying 'libraries>libraries'>Cdrive or documents. Cut the files out of the double folder created in each file and pasted into first library folder of each motor shield files. Then screwed around with the preferences for the 1000th time, changed back to documents and cleared the documents library folder...reopened the documents library and noticed another library folder created itself inside the Arduino (my documents folder) after I changed preferences back to documents...wtf????! lol 


It works fine now...finally!!!! 


Thanks a million for your help Walt. Much appreciated. 


Cheers 
Trent 

----- Original Message -----

**Comment by photodude** [comment] 2016-04-25 17:53
You are Welcome.

Best of luck with your project. If the issue is solved, please close your issue.

**Comment by TM3DDesign** [comment] 2016-04-25 18:47
Hey Walt, 


One more thing. 


Now that I have that figured out, I just want to know for sure where my sketches I create/modify (single Ino files) are to be saved. From what I can understand from the Arduino library tute it says they are saved in your libraries folder...does that mean you just save them in the libraries main folder? 


Also, as far as this pin 9 10 for PWM issue for servo...can I redo code for pin 7 or any of the others from 1-8 in digital pin rack? 

----- Original Message -----

**Comment by kevin-pololu** [comment] 2016-04-25 21:23
Hi, TM3DDesign.

It looks like you are on your way to getting things working with photodude's help, so I'm glad to see you're making progress. As he already pointed out, your initial trouble was probably caused by having the library installed in the wrong place, so it should work now that you've fixed that. His code is likely to be a better starting point for you since our library was only designed to work with a single shield, and it does not provide a straightforward way to remap the PWM pins.

To address your most recent questions:

* The default location for sketches is in your sketchbook folder (on Windows, C:\Users\\\<username>\Documents\Arduino by default), but you can save them anywhere else you want. Arduino will automatically create a subdirectory to put your sketch in (i.e. if you save a sketch named "motors.ino", Arduino will put it in a folder called "motors" within the location you choose).

* Motor and servo control will conflict by default since they both rely on the AVR's Timer 1, which controls PWM on pins 9 and 10 and is also used by the Arduino [Servo library](https://www.arduino.cc/en/Reference/Servo) to generate servo control signals. One way around this is to use alternate servo code that does not rely on Timer 1; for example, the "Controlling a servo with an Arduino Uno" section of our [Zumo Shield user's guide](https://www.pololu.com/docs/0J57) provides some code that lets you control a servo with Timer 2. This might still conflict with photodude's code if it uses the Timer 2 PWM pins for one of the motor shields, though.

By the way, we would much prefer that you ask for help when you encounter a problem instead of letting it frustrate you for a month and then proclaiming that the library does not work. We'd be happy to help you figure out what you're having trouble with. (Note that we try to test our libraries and example code thoroughly before releasing them, and they are used by many people, so it's unlikely that a major problem would go undetected for so long.)

Additionally, posting on the [Pololu Forum](https://forum.pololu.com/) or [contacting us directly](https://www.pololu.com/contact) are better ways to get support unless you're absolutely sure that there is a bug in the library or example code itself. That doesn't look like the case here, so I'm going to close this GitHub issue, but you and photodude are welcome to continue your discussion. Please get in touch with us through the forum or one of the other methods I mentioned if you'd like any additional help working with the shield.

Kevin

**Closed by kevin-pololu** 2016-04-25 21:23 UTC

**Comment by TM3DDesign** [comment] 2016-04-26 18:03
Hello Kevin, 


Yes I finally was able to get the code to compile and upload but still issues with the driver shield 'flickering' occasionally as the way the shield is designed. The shield gets obstructed with the usb and dc hubs and does allow board to fully connect all pins and the headers are very difficult to keep tight solder connections under board. Have read and seen numerous tutes where people don't even solder all the connections so not entirely certain what exactly is shorting out or what have you. Going to take apart and solder all the pins I think. 


And yes, that is why it was so frustrating as I scoured the internet to find out why the 'default' documents library as you and the Arduino site states does not work when I use that as the default and now works with putting files in cdrive...who knows and don't really care as it is finally working and able to move on with project finally. Although very grateful they are available, I will advise that Github look into the naming conventions of the files provided, as numerous files have very poor naming conventions...not used to that in my field of 3D Modeling and design, as poor naming conventions have 'disastrous' implications for any file directory in all mechanical design software. 


Appreciate the tips for bypassing timer 1 issue with servo, very hard to find someone who really knows or knows how to properly explain what is required to do so. 


All good if that tip works, and thank you for getting back to me. 


Trent 

----- Original Message -----

**Comment by photodude** [comment] 2016-08-15 04:28
@TM3DDesign The hardware changes are listed in the manual - https://www.pololu.com/docs/0J49/6.a

As for software, it's arduino-board specific... From my version of the library
for all custom pins use `DualVNH5019MotorShieldMod3::DualVNH5019MotorShieldMod3(unsigned char INA1, unsigned char INB1, unsigned char EN1DIAG1, unsigned char CS1, unsigned char INA2, unsigned char INB2, unsigned char EN2DIAG2, unsigned char CS2, unsigned char INA3, unsigned char INB3, unsigned char EN3DIAG3, unsigned char CS3, unsigned char INA4, unsigned char INB4, unsigned char EN4DIAG4, unsigned char CS4, unsigned char PWM1, unsigned char PWM2, unsigned char PWM3, unsigned char PWM4)` to specify the analog and PWM pins you have wired the two DualVNH5019MotorShields into


I recommend reading [the timers section of the readme in my version of the library](https://github.com/photodude/DualVNH5019MotorShieldMod3#notes-about-timers) as it will help you with the servo issues.
